export interface CategoryItem {
  id: string
  name: string
  emoji: string
  soundKey: string
  actionDescription: string
  promptText: string
  acceptedAliases: string[]
  bgGradient: string
  minAgeMonths: number
  category: 'farm' | 'dinosaurs' | 'fruits' | 'colors' | 'body' | 'numbers'
}

export type AnimalItem = CategoryItem

export interface CategoryInfo {
  id: 'farm' | 'dinosaurs' | 'fruits' | 'colors' | 'body' | 'numbers'
  name: string
  emoji: string
  description: string
  color: string
}

export const WORD_CATEGORIES: CategoryInfo[] = [
  {
    id: 'farm',
    name: 'Fazenda',
    emoji: '🐮',
    description: 'Bichinhos da fazenda e da selva com seus sons característicos',
    color: '#FF7A45',
  },
  {
    id: 'dinosaurs',
    name: 'Dinossauros',
    emoji: '🦖',
    description: 'T-Rex, Tricerátops, Braquiossauro e grandes criaturas jurássicas',
    color: '#10B981',
  },
  {
    id: 'fruits',
    name: 'Frutas',
    emoji: '🍎',
    description: 'Frutas deliciosas, cores e sabores saudáveis',
    color: '#F43F5E',
  },
  {
    id: 'colors',
    name: 'Cores',
    emoji: '🎨',
    description: 'Vermelho, azul, amarelo e o arco-íris de cores',
    color: '#8B5CF6',
  },
  {
    id: 'body',
    name: 'Corpo',
    emoji: '👀',
    description: 'Partes do corpo: olhos, nariz, boca, mãozinhas e pezinhos',
    color: '#EC4899',
  },
  {
    id: 'numbers',
    name: 'Números',
    emoji: '🔢',
    description: 'Contagem divertida do 1 ao 10 com estímulos visuais',
    color: '#3B82F6',
  },
]

export const FARM_ANIMALS: CategoryItem[] = [
  {
    id: 'leao',
    name: 'Leão',
    emoji: '🦁',
    soundKey: 'leao',
    actionDescription: 'O leão é o rei da selva e solta um rugido bem forte: Roaaar!',
    promptText: 'Agora é a sua vez! Fale: Leão!',
    acceptedAliases: ['leao', 'leão', 'rei leao', 'rugido', 'miau grande', 'rau'],
    bgGradient: 'from-amber-400 to-orange-500',
    minAgeMonths: 12,
    category: 'farm',
  },
  {
    id: 'vaca',
    name: 'Vaca',
    emoji: '🐮',
    soundKey: 'vaca',
    actionDescription: 'A vaquinha vive no pasto e faz: Muuu!',
    promptText: 'Agora fale bem bonito: Vaca!',
    acceptedAliases: ['vaca', 'vaquinha', 'mu', 'muu', 'muuu', 'bicho mu'],
    bgGradient: 'from-emerald-400 to-teal-600',
    minAgeMonths: 12,
    category: 'farm',
  },
  {
    id: 'pato',
    name: 'Pato',
    emoji: '🦆',
    soundKey: 'pato',
    actionDescription: 'O patinho nada na lagoa e faz: Quá quá!',
    promptText: 'Agora repita com o Tico: Pato!',
    acceptedAliases: ['pato', 'patinho', 'qua', 'qua qua', 'quack'],
    bgGradient: 'from-sky-400 to-blue-600',
    minAgeMonths: 12,
    category: 'farm',
  },
  {
    id: 'gato',
    name: 'Gato',
    emoji: '🐱',
    soundKey: 'gato',
    actionDescription: 'O gatinho adora carinho e faz: Miau miau!',
    promptText: 'Agora fale: Gato!',
    acceptedAliases: ['gato', 'gatinho', 'miau', 'miau miau', 'miauzinho'],
    bgGradient: 'from-purple-400 to-indigo-600',
    minAgeMonths: 12,
    category: 'farm',
  },
  {
    id: 'cachorro',
    name: 'Cachorro',
    emoji: '🐶',
    soundKey: 'cachorro',
    actionDescription: 'O cachorrinho abana o rabinho e faz: Au au!',
    promptText: 'Agora fale: Cachorro!',
    acceptedAliases: ['cachorro', 'cachorrinho', 'cao', 'cão', 'au au', 'auau', 'toto', 'totó'],
    bgGradient: 'from-amber-500 to-yellow-600',
    minAgeMonths: 12,
    category: 'farm',
  },
  {
    id: 'ovelha',
    name: 'Ovelha',
    emoji: '🐑',
    soundKey: 'ovelha',
    actionDescription: 'A ovelhinha tem lã fofinha e faz: Mééé!',
    promptText: 'Agora fale: Ovelha!',
    acceptedAliases: ['ovelha', 'ovelhinha', 'me', 'meee', 'mé', 'mééé'],
    bgGradient: 'from-rose-400 to-pink-600',
    minAgeMonths: 12,
    category: 'farm',
  },
  {
    id: 'elefante',
    name: 'Elefante',
    emoji: '🐘',
    soundKey: 'elefante',
    actionDescription: 'O elefante tem uma tromba gigante e faz um som estrondoso!',
    promptText: 'Agora tente falar: Elefante!',
    acceptedAliases: ['elefante', 'elefantinho', 'fante', 'tromba'],
    bgGradient: 'from-cyan-500 to-blue-700',
    minAgeMonths: 18,
    category: 'farm',
  },
  {
    id: 'macaco',
    name: 'Macaco',
    emoji: '🐒',
    soundKey: 'macaco',
    actionDescription: 'O macaco pula nos galhos e faz: Uh uh ah ah!',
    promptText: 'Agora fale: Macaco!',
    acceptedAliases: ['macaco', 'macaquinho', 'uh uh', 'uh uh ah ah', 'caco'],
    bgGradient: 'from-orange-500 to-amber-700',
    minAgeMonths: 18,
    category: 'farm',
  },
  {
    id: 'porco',
    name: 'Porquinho',
    emoji: '🐷',
    soundKey: 'porco',
    actionDescription: 'O porquinho adora poça de lama e faz: Oinc oinc!',
    promptText: 'Agora fale: Porquinho!',
    acceptedAliases: ['porco', 'porquinho', 'oinc', 'oinc oinc', 'pig'],
    bgGradient: 'from-pink-400 to-rose-500',
    minAgeMonths: 12,
    category: 'farm',
  },
  {
    id: 'cavalo',
    name: 'Cavalo',
    emoji: '🐴',
    soundKey: 'cavalo',
    actionDescription: 'O cavalinho corre veloz no campo e relincha: Iiirrrí!',
    promptText: 'Agora repita: Cavalo!',
    acceptedAliases: ['cavalo', 'cavalinho', 'pocoto', 'pocotó', 'iii', 'relincho'],
    bgGradient: 'from-amber-600 to-stone-700',
    minAgeMonths: 18,
    category: 'farm',
  },
  {
    id: 'galinha',
    name: 'Galinha',
    emoji: '🐔',
    soundKey: 'galinha',
    actionDescription: 'A galinha choca seus ovinhos e faz: Có có có!',
    promptText: 'Agora fale com o Tico: Galinha!',
    acceptedAliases: ['galinha', 'galinhazinha', 'co co', 'có có', 'galo', 'cocó'],
    bgGradient: 'from-yellow-400 to-amber-600',
    minAgeMonths: 12,
    category: 'farm',
  },
  {
    id: 'sapo',
    name: 'Sapo',
    emoji: '🐸',
    soundKey: 'sapo',
    actionDescription: 'O sapo pula na beira da lagoa e faz: Croac croac!',
    promptText: 'Agora fale bem alto: Sapo!',
    acceptedAliases: ['sapo', 'sapinho', 'croac', 'croac croac', 'cururu'],
    bgGradient: 'from-emerald-500 to-green-700',
    minAgeMonths: 12,
    category: 'farm',
  },
]

export const DINOSAURS: CategoryItem[] = [
  {
    id: 'trex',
    name: 'Tiranossauro Rex',
    emoji: '🦖',
    soundKey: 'trex',
    actionDescription: 'O T-Rex é o rei dos dinos, tem dentes afiados e ruge: GROOAAAR!',
    promptText: 'Agora solte o rugido e fale: T-Rex!',
    acceptedAliases: [
      'trex',
      't-rex',
      'tiranossauro',
      'tiranossauro rex',
      't rex',
      'dino rex',
      'rex',
    ],
    bgGradient: 'from-emerald-500 to-teal-700',
    minAgeMonths: 18,
    category: 'dinosaurs',
  },
  {
    id: 'triceratops',
    name: 'Tricerátops',
    emoji: '🦏',
    soundKey: 'triceratops',
    actionDescription: 'O Tricerátops tem três chifres fortes para se proteger!',
    promptText: 'Agora repita bem forte: Tricerátops!',
    acceptedAliases: ['triceratops', 'triceratop', 'tricerátops', 'chifre', 'dino chifre'],
    bgGradient: 'from-amber-500 to-orange-700',
    minAgeMonths: 24,
    category: 'dinosaurs',
  },
  {
    id: 'braquiossauro',
    name: 'Braquiossauro',
    emoji: '🦕',
    soundKey: 'braquiossauro',
    actionDescription: 'O Braquiossauro tem um pescoço gigante que alcança as copas das árvores!',
    promptText: 'Agora fale esticando a voz: Braquiossauro!',
    acceptedAliases: ['braquiossauro', 'braquio', 'pescoco comprido', 'pescoçudo', 'diplodoco'],
    bgGradient: 'from-sky-500 to-cyan-700',
    minAgeMonths: 18,
    category: 'dinosaurs',
  },
  {
    id: 'estegossauro',
    name: 'Estegossauro',
    emoji: '🦎',
    soundKey: 'estegossauro',
    actionDescription: 'O Estegossauro tem placas triangulares brilhantes nas costas!',
    promptText: 'Agora diga: Estegossauro!',
    acceptedAliases: ['estegossauro', 'estego', 'espinho', 'placas'],
    bgGradient: 'from-violet-500 to-purple-800',
    minAgeMonths: 24,
    category: 'dinosaurs',
  },
  {
    id: 'velociraptor',
    name: 'Velociraptor',
    emoji: '🦖',
    soundKey: 'velociraptor',
    actionDescription: 'O Velociraptor é super veloz, esperto e corre como o vento!',
    promptText: 'Agora diga rápido: Velociraptor!',
    acceptedAliases: ['velociraptor', 'raptor', 'veloz', 'dino rapido'],
    bgGradient: 'from-red-500 to-rose-700',
    minAgeMonths: 24,
    category: 'dinosaurs',
  },
  {
    id: 'pterodatilo',
    name: 'Pterodátilo',
    emoji: '🦅',
    soundKey: 'pterodatilo',
    actionDescription: 'O Pterodátilo voa nas nuvens com asas abertas e dá um grito jurássico!',
    promptText: 'Agora voe como dino e fale: Pterodátilo!',
    acceptedAliases: ['pterodatilo', 'pterodátilo', 'passaro dino', 'asa dino', 'voador'],
    bgGradient: 'from-blue-400 to-indigo-600',
    minAgeMonths: 24,
    category: 'dinosaurs',
  },
  {
    id: 'anquilossauro',
    name: 'Anquilossauro',
    emoji: '🐢',
    soundKey: 'anquilossauro',
    actionDescription: 'O Anquilossauro tem uma couraça de pedra e um martelo na cauda!',
    promptText: 'Agora fale: Anquilossauro!',
    acceptedAliases: ['anquilossauro', 'anquilo', 'tartaruga dino', 'couraça', 'cauda martelo'],
    bgGradient: 'from-stone-500 to-zinc-800',
    minAgeMonths: 24,
    category: 'dinosaurs',
  },
  {
    id: 'espinossauro',
    name: 'Espinossauro',
    emoji: '🐊',
    soundKey: 'espinossauro',
    actionDescription: 'O Espinossauro nada nos rios e tem uma grande vela nas costas!',
    promptText: 'Agora fale: Espinossauro!',
    acceptedAliases: ['espinossauro', 'espino', 'dino vela', 'dino agua'],
    bgGradient: 'from-teal-500 to-emerald-800',
    minAgeMonths: 24,
    category: 'dinosaurs',
  },
]

export const FRUITS: CategoryItem[] = [
  {
    id: 'banana',
    name: 'Banana',
    emoji: '🍌',
    soundKey: 'crunch',
    actionDescription: 'A banana é amarelinha, docinha e a favorita dos macaquinhos: Nham!',
    promptText: 'Agora fale com o Tico: Banana!',
    acceptedAliases: ['banana', 'nanica', 'bananinha', 'nana'],
    bgGradient: 'from-yellow-400 to-amber-500',
    minAgeMonths: 12,
    category: 'fruits',
  },
  {
    id: 'maca',
    name: 'Maçã',
    emoji: '🍎',
    soundKey: 'crunch',
    actionDescription: 'A maçã é vermelhinha, crocante e muito suculenta: Crunc!',
    promptText: 'Agora fale bem alto: Maçã!',
    acceptedAliases: ['maca', 'maçã', 'macazinha', 'maca vermelha'],
    bgGradient: 'from-red-400 to-rose-600',
    minAgeMonths: 12,
    category: 'fruits',
  },
  {
    id: 'uva',
    name: 'Uva',
    emoji: '🍇',
    soundKey: 'pop_soft',
    actionDescription: 'A uva vem em cachos roxinhos e doces: Plop!',
    promptText: 'Agora fale: Uva!',
    acceptedAliases: ['uva', 'uvinha', 'cacho de uva'],
    bgGradient: 'from-purple-500 to-indigo-700',
    minAgeMonths: 12,
    category: 'fruits',
  },
  {
    id: 'laranja',
    name: 'Laranja',
    emoji: '🍊',
    soundKey: 'splash',
    actionDescription: 'A laranja dá um suco refrescante e cheio de vitamina C: Shhh!',
    promptText: 'Agora repita: Laranja!',
    acceptedAliases: ['laranja', 'laranjinha', 'suco'],
    bgGradient: 'from-orange-400 to-amber-600',
    minAgeMonths: 12,
    category: 'fruits',
  },
  {
    id: 'morango',
    name: 'Morango',
    emoji: '🍓',
    soundKey: 'crunch',
    actionDescription: 'O moranguinho é vermelhinho com pintinhas e muito cheiroso!',
    promptText: 'Agora diga: Morango!',
    acceptedAliases: ['morango', 'moranguinho'],
    bgGradient: 'from-rose-500 to-red-600',
    minAgeMonths: 12,
    category: 'fruits',
  },
  {
    id: 'melancia',
    name: 'Melancia',
    emoji: '🍉',
    soundKey: 'splash',
    actionDescription: 'A melancia é verde por fora, vermelha por dentro e cheia de água!',
    promptText: 'Agora fale: Melancia!',
    acceptedAliases: ['melancia', 'melancinha', 'melão'],
    bgGradient: 'from-emerald-400 to-rose-600',
    minAgeMonths: 18,
    category: 'fruits',
  },
  {
    id: 'abacaxi',
    name: 'Abacaxi',
    emoji: '🍍',
    soundKey: 'crunch',
    actionDescription: 'O abacaxi tem uma coroa de rei e um sabor tropical delicioso!',
    promptText: 'Agora fale: Abacaxi!',
    acceptedAliases: ['abacaxi', 'ananas', 'ananás'],
    bgGradient: 'from-amber-400 to-yellow-600',
    minAgeMonths: 18,
    category: 'fruits',
  },
  {
    id: 'pera',
    name: 'Pera',
    emoji: '🍐',
    soundKey: 'crunch',
    actionDescription: 'A pera é macia, verdinha e refrescante!',
    promptText: 'Agora fale: Pera!',
    acceptedAliases: ['pera', 'perinha', 'pêra'],
    bgGradient: 'from-lime-400 to-emerald-600',
    minAgeMonths: 12,
    category: 'fruits',
  },
]

export const COLORS: CategoryItem[] = [
  {
    id: 'vermelho',
    name: 'Vermelho',
    emoji: '🔴',
    soundKey: 'chime_c',
    actionDescription: 'O vermelho é a cor do coração, do morango e da maçã!',
    promptText: 'Agora fale a cor: Vermelho!',
    acceptedAliases: ['vermelho', 'vermelha', 'cor vermelha', 'red'],
    bgGradient: 'from-red-500 to-rose-700',
    minAgeMonths: 12,
    category: 'colors',
  },
  {
    id: 'azul',
    name: 'Azul',
    emoji: '🔵',
    soundKey: 'chime_e',
    actionDescription: 'O azul é a cor do céu aberto e do mar infinito!',
    promptText: 'Agora fale: Azul!',
    acceptedAliases: ['azul', 'cor azul', 'blue'],
    bgGradient: 'from-sky-500 to-blue-700',
    minAgeMonths: 12,
    category: 'colors',
  },
  {
    id: 'amarelo',
    name: 'Amarelo',
    emoji: '🟡',
    soundKey: 'chime_g',
    actionDescription: 'O amarelo é a cor do sol brilhante, do girassol e da banana!',
    promptText: 'Agora fale a cor: Amarelo!',
    acceptedAliases: ['amarelo', 'amarela', 'cor amarela', 'yellow'],
    bgGradient: 'from-amber-400 to-yellow-500',
    minAgeMonths: 12,
    category: 'colors',
  },
  {
    id: 'verde',
    name: 'Verde',
    emoji: '🟢',
    soundKey: 'chime_c_high',
    actionDescription: 'O verde é a cor da natureza, das folhas e da floresta!',
    promptText: 'Agora fale: Verde!',
    acceptedAliases: ['verde', 'cor verde', 'green'],
    bgGradient: 'from-emerald-500 to-green-700',
    minAgeMonths: 12,
    category: 'colors',
  },
  {
    id: 'roxo',
    name: 'Roxo',
    emoji: '🟣',
    soundKey: 'chime_e',
    actionDescription: 'O roxo é a cor da uva, da violeta e da mágica!',
    promptText: 'Agora diga: Roxo!',
    acceptedAliases: ['roxo', 'roxa', 'cor roxa', 'violeta', 'purpura'],
    bgGradient: 'from-purple-500 to-indigo-700',
    minAgeMonths: 18,
    category: 'colors',
  },
  {
    id: 'laranja_cor',
    name: 'Laranja',
    emoji: '🟠',
    soundKey: 'chime_g',
    actionDescription: 'O laranja é alegre, quente como o entardecer!',
    promptText: 'Agora fale: Laranja!',
    acceptedAliases: ['laranja', 'alaranjado', 'cor laranja', 'orange'],
    bgGradient: 'from-orange-400 to-amber-600',
    minAgeMonths: 18,
    category: 'colors',
  },
  {
    id: 'rosa',
    name: 'Rosa',
    emoji: '🌸',
    soundKey: 'chime_c_high',
    actionDescription: 'O rosa é a cor das flores doces e do flamingo!',
    promptText: 'Agora fale: Rosa!',
    acceptedAliases: ['rosa', 'cor de rosa', 'cor rosa', 'pink'],
    bgGradient: 'from-pink-400 to-rose-500',
    minAgeMonths: 18,
    category: 'colors',
  },
  {
    id: 'preto',
    name: 'Preto',
    emoji: '⚫',
    soundKey: 'chime_c',
    actionDescription: 'O preto é a cor da noite escura cheia de estrelas!',
    promptText: 'Agora fale: Preto!',
    acceptedAliases: ['preto', 'preta', 'cor preta', 'black'],
    bgGradient: 'from-slate-700 to-slate-900',
    minAgeMonths: 24,
    category: 'colors',
  },
  {
    id: 'branco',
    name: 'Branco',
    emoji: '⚪',
    soundKey: 'chime_e',
    actionDescription: 'O branco é a cor das nuvens fofinhas e do algodão!',
    promptText: 'Agora fale: Branco!',
    acceptedAliases: ['branco', 'branca', 'cor branca', 'white'],
    bgGradient: 'from-slate-300 to-slate-500',
    minAgeMonths: 24,
    category: 'colors',
  },
]

export const BODY_PARTS: CategoryItem[] = [
  {
    id: 'olho',
    name: 'Olho',
    emoji: '👀',
    soundKey: 'blink',
    actionDescription: 'Com os olhos nós enxergamos o mundo e piscamos: Pisque pisque!',
    promptText: 'Agora fale: Olho!',
    acceptedAliases: ['olho', 'olhos', 'olhinho', 'olhinhos', 'olhar'],
    bgGradient: 'from-sky-400 to-blue-600',
    minAgeMonths: 12,
    category: 'body',
  },
  {
    id: 'nariz',
    name: 'Nariz',
    emoji: '👃',
    soundKey: 'sniff',
    actionDescription: 'Com o nariz nós sentimos o cheirinho das flores: Sniff sniff!',
    promptText: 'Agora fale: Nariz!',
    acceptedAliases: ['nariz', 'narizinho', 'focinho', 'cheiro'],
    bgGradient: 'from-amber-400 to-orange-500',
    minAgeMonths: 12,
    category: 'body',
  },
  {
    id: 'boca',
    name: 'Boca',
    emoji: '👄',
    soundKey: 'kiss',
    actionDescription: 'Com a boca nós conversamos, cantamos e damos risada: Haha!',
    promptText: 'Agora fale: Boca!',
    acceptedAliases: ['boca', 'boquinha', 'labios', 'dentes', 'sorriso'],
    bgGradient: 'from-rose-400 to-red-600',
    minAgeMonths: 12,
    category: 'body',
  },
  {
    id: 'orelha',
    name: 'Ouvido',
    emoji: '👂',
    soundKey: 'bell',
    actionDescription: 'Com os ouvidos nós escutamos as historinhas e as musiquinhas!',
    promptText: 'Agora fale: Ouvido!',
    acceptedAliases: ['ouvido', 'orelha', 'orelhinha', 'escuta', 'audicao'],
    bgGradient: 'from-purple-400 to-indigo-600',
    minAgeMonths: 12,
    category: 'body',
  },
  {
    id: 'mao',
    name: 'Mão',
    emoji: '✋',
    soundKey: 'clap',
    actionDescription: 'Com as mãos nós batemos palminhas: Palmas palmas!',
    promptText: 'Agora fale: Mão!',
    acceptedAliases: ['mao', 'mão', 'maozinha', 'mãozinha', 'palma', 'dedos'],
    bgGradient: 'from-emerald-400 to-teal-600',
    minAgeMonths: 12,
    category: 'body',
  },
  {
    id: 'pe',
    name: 'Pé',
    emoji: '🦶',
    soundKey: 'step',
    actionDescription: 'Com os pés nós pulamos, corremos e dançamos: Pula pula!',
    promptText: 'Agora fale: Pé!',
    acceptedAliases: ['pe', 'pé', 'pezinho', 'pezinhos', 'sapato'],
    bgGradient: 'from-cyan-500 to-blue-700',
    minAgeMonths: 12,
    category: 'body',
  },
  {
    id: 'cabeca',
    name: 'Cabeça',
    emoji: '👶',
    soundKey: 'tap',
    actionDescription: 'Na cabeça mora o cérebro que pensa, imagina e aprende!',
    promptText: 'Agora diga: Cabeça!',
    acceptedAliases: ['cabeca', 'cabeça', 'cabecinha', 'cabelo'],
    bgGradient: 'from-amber-500 to-yellow-600',
    minAgeMonths: 18,
    category: 'body',
  },
  {
    id: 'barriga',
    name: 'Barriga',
    emoji: '🤰',
    soundKey: 'tickle',
    actionDescription: 'A barriguinha guarda o lanchinho e adora cosquinha: Cócegas!',
    promptText: 'Agora fale: Barriga!',
    acceptedAliases: ['barriga', 'barriguinha', 'pança', 'bucho', 'umbigo'],
    bgGradient: 'from-pink-400 to-rose-500',
    minAgeMonths: 18,
    category: 'body',
  },
]

export const NUMBERS: CategoryItem[] = [
  {
    id: 'num_1',
    name: 'Um',
    emoji: '1️⃣',
    soundKey: 'num_1',
    actionDescription: 'Número 1! Um sol brilhando no céu!',
    promptText: 'Agora fale o número: Um!',
    acceptedAliases: ['um', '1', 'numero um', 'número um', 'uma'],
    bgGradient: 'from-sky-400 to-blue-600',
    minAgeMonths: 18,
    category: 'numbers',
  },
  {
    id: 'num_2',
    name: 'Dois',
    emoji: '2️⃣',
    soundKey: 'num_2',
    actionDescription: 'Número 2! Dois olhinhos para enxergar!',
    promptText: 'Agora fale: Dois!',
    acceptedAliases: ['dois', '2', 'numero dois', 'número dois', 'duas'],
    bgGradient: 'from-emerald-400 to-teal-600',
    minAgeMonths: 18,
    category: 'numbers',
  },
  {
    id: 'num_3',
    name: 'Três',
    emoji: '3️⃣',
    soundKey: 'num_3',
    actionDescription: 'Número 3! Três patinhos nadando na lagoa!',
    promptText: 'Agora diga: Três!',
    acceptedAliases: ['tres', 'três', '3', 'numero tres', 'número três'],
    bgGradient: 'from-amber-400 to-orange-500',
    minAgeMonths: 18,
    category: 'numbers',
  },
  {
    id: 'num_4',
    name: 'Quatro',
    emoji: '4️⃣',
    soundKey: 'num_4',
    actionDescription: 'Número 4! Quatro patas do cachorrinho!',
    promptText: 'Agora fale: Quatro!',
    acceptedAliases: ['quatro', '4', 'numero quatro', 'número quatro'],
    bgGradient: 'from-purple-400 to-indigo-600',
    minAgeMonths: 24,
    category: 'numbers',
  },
  {
    id: 'num_5',
    name: 'Cinco',
    emoji: '5️⃣',
    soundKey: 'num_5',
    actionDescription: 'Número 5! Cinco dedinhos na mãozinha!',
    promptText: 'Agora fale: Cinco!',
    acceptedAliases: ['cinco', '5', 'numero cinco', 'número cinco'],
    bgGradient: 'from-rose-400 to-pink-600',
    minAgeMonths: 24,
    category: 'numbers',
  },
  {
    id: 'num_6',
    name: 'Seis',
    emoji: '6️⃣',
    soundKey: 'num_6',
    actionDescription: 'Número 6! Seis bolhas subindo no ar!',
    promptText: 'Agora fale: Seis!',
    acceptedAliases: ['seis', '6', 'numero seis', 'número seis', 'meia'],
    bgGradient: 'from-cyan-500 to-blue-700',
    minAgeMonths: 24,
    category: 'numbers',
  },
  {
    id: 'num_7',
    name: 'Sete',
    emoji: '7️⃣',
    soundKey: 'num_7',
    actionDescription: 'Número 7! Sete cores no arco-íris!',
    promptText: 'Agora fale: Sete!',
    acceptedAliases: ['sete', '7', 'numero sete', 'número sete'],
    bgGradient: 'from-violet-400 to-purple-600',
    minAgeMonths: 30,
    category: 'numbers',
  },
  {
    id: 'num_8',
    name: 'Oito',
    emoji: '8️⃣',
    soundKey: 'num_8',
    actionDescription: 'Número 8! Oito tentáculos do polvo!',
    promptText: 'Agora fale: Oito!',
    acceptedAliases: ['oito', '8', 'numero oito', 'número oito'],
    bgGradient: 'from-amber-500 to-yellow-600',
    minAgeMonths: 30,
    category: 'numbers',
  },
  {
    id: 'num_9',
    name: 'Nove',
    emoji: '9️⃣',
    soundKey: 'num_9',
    actionDescription: 'Número 9! Quase dez, que legal!',
    promptText: 'Agora fale: Nove!',
    acceptedAliases: ['nove', '9', 'numero nove', 'número nove'],
    bgGradient: 'from-lime-500 to-emerald-600',
    minAgeMonths: 30,
    category: 'numbers',
  },
  {
    id: 'num_10',
    name: 'Dez',
    emoji: '🔟',
    soundKey: 'num_10',
    actionDescription: 'Número 10! As duas mãozinhas cheias de dedinhos!',
    promptText: 'Agora comemore e fale: Dez!',
    acceptedAliases: ['dez', '10', 'numero dez', 'número dez'],
    bgGradient: 'from-fuchsia-500 to-rose-600',
    minAgeMonths: 30,
    category: 'numbers',
  },
]

export const ALL_CATEGORY_ITEMS: Record<string, CategoryItem[]> = {
  farm: FARM_ANIMALS,
  dinosaurs: DINOSAURS,
  fruits: FRUITS,
  colors: COLORS,
  body: BODY_PARTS,
  numbers: NUMBERS,
}

export function getItemsByCategory(categoryId: string): CategoryItem[] {
  return ALL_CATEGORY_ITEMS[categoryId] || FARM_ANIMALS
}

export function getAllItems(): CategoryItem[] {
  return [...FARM_ANIMALS, ...DINOSAURS, ...FRUITS, ...COLORS, ...BODY_PARTS, ...NUMBERS]
}
